#!/bin/bash

set -e

echo "Generating protos..."
go get google.golang.org/protobuf/cmd/protoc-gen-go
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc

gopath=$(go env GOPATH)
proto_files=$(find protos/v22.10 -name "*.proto")
for proto in $proto_files
do
    echo "Proto $proto"
    proto_base_name=$(basename "$proto" .proto)
    mkdir -p protos/v22.10/"$proto_base_name"
    echo "Compiling $proto_base_name.proto ..."
    tools/protobuf/bin/protoc --proto_path="$PWD"/protos/v22.10 --go_out=./protos/v22.10/"$proto_base_name" --go-grpc_out=./protos/v22.10/"$proto_base_name" --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --plugin=protoc-gen-go=$gopath/bin/protoc-gen-go --plugin=protoc-gen-go-grpc="$gopath"/bin/protoc-gen-go-grpc "$PWD"/protos/v22.10/"$proto_base_name.proto"
    echo "done."
done

echo "Protobuf code generation completed!"