// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package monitoring

//go:generate mockgen -source=monitoring_grpc.pb.go -destination=monitoring_grpc.pb_mock.go -package=monitoring

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MonitoringClient is the client API for Monitoring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitoringClient interface {
	Stats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (Monitoring_StatsClient, error)
}

type monitoringClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringClient(cc grpc.ClientConnInterface) MonitoringClient {
	return &monitoringClient{cc}
}

func (c *monitoringClient) Stats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (Monitoring_StatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Monitoring_ServiceDesc.Streams[0], "/event_store.client.monitoring.Monitoring/Stats", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitoringStatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Monitoring_StatsClient interface {
	Recv() (*StatsResp, error)
	grpc.ClientStream
}

type monitoringStatsClient struct {
	grpc.ClientStream
}

func (x *monitoringStatsClient) Recv() (*StatsResp, error) {
	m := new(StatsResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitoringServer is the server API for Monitoring service.
// All implementations must embed UnimplementedMonitoringServer
// for forward compatibility
type MonitoringServer interface {
	Stats(*StatsReq, Monitoring_StatsServer) error
	mustEmbedUnimplementedMonitoringServer()
}

// UnimplementedMonitoringServer must be embedded to have forward compatible implementations.
type UnimplementedMonitoringServer struct{}

func (UnimplementedMonitoringServer) Stats(*StatsReq, Monitoring_StatsServer) error {
	return status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedMonitoringServer) mustEmbedUnimplementedMonitoringServer() {}

// UnsafeMonitoringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServer will
// result in compilation errors.
type UnsafeMonitoringServer interface {
	mustEmbedUnimplementedMonitoringServer()
}

func RegisterMonitoringServer(s grpc.ServiceRegistrar, srv MonitoringServer) {
	s.RegisterService(&Monitoring_ServiceDesc, srv)
}

func _Monitoring_Stats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitoringServer).Stats(m, &monitoringStatsServer{stream})
}

type Monitoring_StatsServer interface {
	Send(*StatsResp) error
	grpc.ServerStream
}

type monitoringStatsServer struct {
	grpc.ServerStream
}

func (x *monitoringStatsServer) Send(m *StatsResp) error {
	return x.ServerStream.SendMsg(m)
}

// Monitoring_ServiceDesc is the grpc.ServiceDesc for Monitoring service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monitoring_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event_store.client.monitoring.Monitoring",
	HandlerType: (*MonitoringServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stats",
			Handler:       _Monitoring_Stats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monitoring.proto",
}
