name: Build
on:
    pull_request:
    push:
        branches:
            - develop
jobs:
    build:
        name: Code generation & compile
        strategy:
            matrix:
                include:
                    - target: ubuntu-18.04
                    - target: windows-2019
                    - target: macos-10.15


        runs-on: ${{ matrix.target }}

        steps:
            - uses: actions/checkout@v1

            - name: Cache tests
              id: cache
              uses: actions/cache@v2
              with:
                  path: ./README.md
                  key: ${{ runner.os }}-build-${{ hashFiles('core/**', 'protos/**', 'client/**', 'event_streams/**', 'projections/**', 'persistent/**', 'operations/**', 'user_management/**') }}

            - name: Generate protos and build project (Powershell)
              if: ${{ matrix.os == 'windows-2019' && steps.cache.outputs.cache-hit != 'true' }}
              run: .\build.ps1 -generateProtos
              shell: pwsh

            - name: Generate protos and build project (Bash)
              if: ${{ matrix.os != 'windows-2019' && steps.cache.outputs.cache-hit != 'true' }}
              run: ./build.sh --generate-protos