name: Integration Tests With Prepopulated Database
on:
    pull_request:
    push:
        branches:
            - develop
jobs:
    integration-tests-with-prepopulated-database:
        strategy:
            matrix:
                include:
                    - target: event_streams
                      source_dir: 'event_streams/**'
                      test_dir: './integration_tests/internal/with_prepopulated_database/event_streams/**'
            fail-fast: false
        runs-on: ubuntu-18.04

        name: Test - ${{ matrix.domain }}

        steps:
            -   uses: actions/checkout@v1

            -   name: Cache tests
                id: cache
                uses: actions/cache@v2
                with:
                    path: ./README.md
                    key: ${{ runner.os }}-integration-prepop-db-test-${{ hashFiles(matrix.test_dir, matrix.source_dir, 'core/**', 'protos/**') }}

            -   name: Docker Login
                if: ${{ steps.cache.outputs.cache-hit != 'true' }}
                run: |
                    (echo ${{ secrets.GITHUB_TOKEN }} | docker login -u pivonroll --password-stdin docker.pkg.github.com) || \
                    (echo ${{ secrets.GITHUB_TOKEN }} | docker login -u pivonroll --password-stdin docker.pkg.github.com) || \
                    (echo ${{ secrets.GITHUB_TOKEN }} | docker login -u pivonroll --password-stdin docker.pkg.github.com) || \
                    (exit 1)
                    (docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:21.6.0-buster-slim) || \
                    (docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:21.6.0-buster-slim) || \
                    (docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:21.6.0-buster-slim) || \
                    (docker pull docker.pkg.github.com/eventstore/eventstore-client-grpc-testdata/eventstore-client-grpc-testdata:21.6.0-buster-slim) || \
                    (exit 1)

            -   name: Tests
                if: ${{ steps.cache.outputs.cache-hit != 'true' }}
                run: |
                    touch vars.env
                    docker-compose up
                    cd integration_tests/internal/with_prepopulated_database/${{ matrix.domain }}
                    go test -v ./...
                    docker-compose down
